<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614154545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE editeur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, editeur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CF5393DF3375BD21 ON ia (editeur_id)');
        $this->addSql('CREATE TABLE ingenieur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, priorite BOOLEAN NOT NULL, version_id INT DEFAULT NULL, ingenieur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA34BBC2705 ON ticket (version_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3331C8F6 ON ticket (ingenieur_id)');
        $this->addSql('CREATE TABLE version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, ia_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF1CD3C3489A6E65 ON version (ia_id)');
        $this->addSql('ALTER TABLE ia ADD CONSTRAINT FK_CF5393DF3375BD21 FOREIGN KEY (editeur_id) REFERENCES editeur (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA34BBC2705 FOREIGN KEY (version_id) REFERENCES version (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3331C8F6 FOREIGN KEY (ingenieur_id) REFERENCES ingenieur (id)');
        $this->addSql('ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C3489A6E65 FOREIGN KEY (ia_id) REFERENCES ia (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ia DROP CONSTRAINT FK_CF5393DF3375BD21');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA34BBC2705');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3331C8F6');
        $this->addSql('ALTER TABLE version DROP CONSTRAINT FK_BF1CD3C3489A6E65');
        $this->addSql('DROP TABLE editeur');
        $this->addSql('DROP TABLE ia');
        $this->addSql('DROP TABLE ingenieur');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE version');
    }
}
