-- Adminer 5.4.2 PostgreSQL 17.10 dump

DROP TABLE IF EXISTS "doctrine_migration_versions";
CREATE TABLE "public"."doctrine_migration_versions" (
    "version" character varying(191) NOT NULL,
    "executed_at" timestamp(0),
    "execution_time" integer,
    CONSTRAINT "doctrine_migration_versions_pkey" PRIMARY KEY ("version")
)
WITH (oids = false);

INSERT INTO "doctrine_migration_versions" ("version", "executed_at", "execution_time") VALUES
( E'DoctrineMigrations\\Version20260614154545',	'2026-06-14 15:45:50',	18);

DROP TABLE IF EXISTS "editeur";
CREATE TABLE "public"."editeur" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    CONSTRAINT "editeur_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);


DROP TABLE IF EXISTS "ia";
CREATE TABLE "public"."ia" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "editeur_id" integer,
    CONSTRAINT "ia_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX idx_cf5393df3375bd21 ON public.ia USING btree (editeur_id);


DROP TABLE IF EXISTS "ingenieur";
CREATE TABLE "public"."ingenieur" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "prenom" character varying(255) NOT NULL,
    CONSTRAINT "ingenieur_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);


DROP TABLE IF EXISTS "ticket";
CREATE TABLE "public"."ticket" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "description" character varying(255) NOT NULL,
    "priorite" boolean NOT NULL,
    "version_id" integer,
    "ingenieur_id" integer,
    CONSTRAINT "ticket_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX idx_97a0ada34bbc2705 ON public.ticket USING btree (version_id);

CREATE INDEX idx_97a0ada3331c8f6 ON public.ticket USING btree (ingenieur_id);


DROP TABLE IF EXISTS "version";
CREATE TABLE "public"."version" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "statut" character varying(255) NOT NULL,
    "ia_id" integer,
    CONSTRAINT "version_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX idx_bf1cd3c3489a6e65 ON public.version USING btree (ia_id);


ALTER TABLE ONLY "public"."ia" ADD CONSTRAINT "fk_cf5393df3375bd21" FOREIGN KEY (editeur_id) REFERENCES editeur(id);

ALTER TABLE ONLY "public"."ticket" ADD CONSTRAINT "fk_97a0ada3331c8f6" FOREIGN KEY (ingenieur_id) REFERENCES ingenieur(id);
ALTER TABLE ONLY "public"."ticket" ADD CONSTRAINT "fk_97a0ada34bbc2705" FOREIGN KEY (version_id) REFERENCES version(id);

ALTER TABLE ONLY "public"."version" ADD CONSTRAINT "fk_bf1cd3c3489a6e65" FOREIGN KEY (ia_id) REFERENCES ia(id);

-- 2026-06-14 15:53:17 UTC