-- Adminer 5.4.2 PostgreSQL 17.10 dump

DROP TABLE IF EXISTS "doctrine_migration_versions";
CREATE TABLE "public"."doctrine_migration_versions" (
    "version" character varying(191) NOT NULL,
    "executed_at" timestamp(0),
    "execution_time" integer,
    CONSTRAINT "doctrine_migration_versions_pkey" PRIMARY KEY ("version")
)
WITH (oids = false);

INSERT INTO "doctrine_migration_versions" ("version", "executed_at", "execution_time") VALUES
( E'DoctrineMigrations\\Version20260614154545',	'2026-06-14 15:45:50',	18),
( E'DoctrineMigrations\\Version20260621081800',	'2026-06-21 08:18:12',	19);

DROP TABLE IF EXISTS "editeur";
CREATE TABLE "public"."editeur" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    CONSTRAINT "editeur_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

INSERT INTO "editeur" ("id", "nom") VALUES
(1,	'OpenIA'),
(2,	'Anthropic'),
(3,	'Google'),
(4,	'Microsoft'),
(5,	'Apple');

DROP TABLE IF EXISTS "ia";
CREATE TABLE "public"."ia" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "editeur_id" integer,
    CONSTRAINT "ia_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX idx_cf5393df3375bd21 ON public.ia USING btree (editeur_id);

INSERT INTO "ia" ("id", "nom", "editeur_id") VALUES
(1,	'ChatGPT',	1),
(2,	'Claude',	2),
(3,	'Gemini',	3),
(4,	'Copilot',	4),
(5,	'Apple Intelligence',	5);

DROP TABLE IF EXISTS "ingenieur";
CREATE TABLE "public"."ingenieur" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "prenom" character varying(255) NOT NULL,
    CONSTRAINT "ingenieur_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

INSERT INTO "ingenieur" ("id", "nom", "prenom") VALUES
(1,	'RUBIO',	'Charles'),
(2,	'REGNIER',	'Hervé');

DROP TABLE IF EXISTS "ticket";
CREATE TABLE "public"."ticket" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "description" character varying(255) NOT NULL,
    "priorite" boolean NOT NULL,
    "version_id" integer,
    "ingenieur_id" integer,
    "create_at" timestamp(0),
    CONSTRAINT "ticket_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX idx_97a0ada34bbc2705 ON public.ticket USING btree (version_id);

CREATE INDEX idx_97a0ada3331c8f6 ON public.ticket USING btree (ingenieur_id);

INSERT INTO "ticket" ("id", "description", "priorite", "version_id", "ingenieur_id", "create_at") VALUES
(7,	'Répond complétement a coté',	't',	8,	2,	NULL),
(8,	'M''a insulté',	'f',	4,	2,	NULL),
(6,	'Ne répond pas',	't',	11,	1,	NULL);

DROP TABLE IF EXISTS "version";
CREATE TABLE "public"."version" (
    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nom" character varying(255) NOT NULL,
    "statut" character varying(255) NOT NULL,
    "ia_id" integer,
    CONSTRAINT "version_pkey" PRIMARY KEY ("id")
)
WITH (oids = false);

CREATE INDEX idx_bf1cd3c3489a6e65 ON public.version USING btree (ia_id);

INSERT INTO "version" ("id", "nom", "statut", "ia_id") VALUES
(3,	'GPT-4.1',	'ok',	1),
(5,	'Sonnet 4.6',	'ok',	2),
(6,	'Opus 4.8',	'ok',	2),
(7,	'Fable 5',	'mid',	2),
(9,	'3.5 Flash',	'ok',	3),
(10,	'3.1 Pro',	'ok',	3),
(8,	'3.1 Flash-Lite',	'pas_ok',	3),
(4,	'Haiku 4.5',	'mid',	2),
(12,	'AFM 3 Core',	'ok',	5),
(2,	'GPT-4o',	'ok',	1),
(1,	'GPT 5-5',	'ok',	1),
(11,	'MCS',	'pas_ok',	4);

ALTER TABLE ONLY "public"."ia" ADD CONSTRAINT "fk_cf5393df3375bd21" FOREIGN KEY (editeur_id) REFERENCES editeur(id);

ALTER TABLE ONLY "public"."ticket" ADD CONSTRAINT "fk_97a0ada3331c8f6" FOREIGN KEY (ingenieur_id) REFERENCES ingenieur(id);
ALTER TABLE ONLY "public"."ticket" ADD CONSTRAINT "fk_97a0ada34bbc2705" FOREIGN KEY (version_id) REFERENCES version(id);

ALTER TABLE ONLY "public"."version" ADD CONSTRAINT "fk_bf1cd3c3489a6e65" FOREIGN KEY (ia_id) REFERENCES ia(id);

-- 2026-06-21 09:13:24 UTC